#!/bin/bash

# Cek dan masuk ke direktori F2RRMining, jika tidak ada, keluarkan pesan error
cd ~/F2RRMining/ || { echo "Base directory tidak ditemukan! Pastikan ~/F2RRMining/ sudah benar."; exit 1; }

# Buang semua perubahan lokal yang belum di-commit
if git reset --hard; then
  echo "Perubahan lokal telah dibuang."
else
  echo "Gagal membuang perubahan lokal."
  exit 1
fi

# Fetch dan pull dari origin/main
if git fetch origin && git pull origin main; then
  echo "Git pull berhasil."
else
  echo "Git pull gagal."
  exit 1
fi

# Kembali ke home directory
cd ~/
