#!/bin/bash

# Cek dan masuk ke direktori F2RRMining, jika tidak ada, keluarkan pesan error
cd ~/F22RMining/ || { echo "Base directory tidak ditemukan! Pastikan ~/F22RMining/ sudah benar."; exit 1; }

# Fetch dari origin dan cek keberhasilannya
if git fetch origin; then
  echo "Git fetch berhasil."
else
  echo "Git fetch gagal. Periksa koneksi atau konfigurasi git Anda."
  exit 1
fi

# Pull dari origin/main dan cek keberhasilannya
if git pull origin main; then
  echo "Git pull berhasil."
else
  echo "Git pull gagal. Periksa konflik atau masalah lainnya."
  exit 1
fi

# Kembali ke home directory
cd ~/
